# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jonathan Medina Herrera
title: Software Developer | Backend Specialist
email: jonathan.medina1312@alumnos.udg.mx / jonathanmedinah0@gmail.com
phone: (52) 33 1915 9066
website: coming soon
darkmode: false

# Social links
github_username: Jonathan-Med
linkedin_username: jonathan-medina-herrera
hackerrank_username: jonathanmedinah0

# About Section
about_profile_image: images/Profile.jpg
about_content: |
  Soy estudiante de último año de Ingeniería en Computación en la Universidad de Guadalajara, con especial interés en el desarrollo backend, redes y ciberseguridad. Mi adaptabilidad y habilidades técnicas me permiten aprender rápidamente nuevas tecnologías, mientras que mi pasión por la tecnología me impulsa a seguir creciendo profesionalmente. Estoy en busca de oportunidades para prácticas o empleo de tiempo completo.

  Habilidades y competencias:
  - Trabajo en equipo
  - Resolución de problemas
  - Adaptabilidad
  - Pensamiento crítico

  Competencias Técnicas:
  - Java, Python, JavaScript
  - MySQL, PostgreSQL
  - Spring Boot, Django
  - Docker, Git
  - Redes, Ciberseguridad

# Projects
content:
  - title: Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: Foro Hub
        additional_links:
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/Jonathan-Med/ForoHub
        description: |
          Sistema de gestión de cursos con operaciones CRUD y seguridad robusta.
          **Tecnologías:** Java, Spring Boot, MySQL, JWT, OpenAPI.

      - layout: left
        border: weak
        title: Literalura
        additional_links:
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/Jonathan-Med/Challenge-Literalura
        description: |
          Sistema para consultar una API y gestionar libros.
          **Tecnologías:** Java, PostgreSQL, Spring Boot, JPA.

      - layout: left
        border: weak
        title: Conversor de Monedas
        additional_links:
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/Jonathan-Med/ConversorDeMonedas
        description: |
          Conversor de monedas para 15 divisas utilizando una API.
          **Tecnologías:** Java, Spring Boot.

      - layout: left
        border: weak
        title: RandomFilterGen
        additional_links:
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/Jonathan-Med/Comp-Tolerante-a-fallas/tree/main/Proyecto-Final/RandomFilterGen/RandomFilterGen-main
        description: |
          Aplicación web que aplica filtros glitch aleatorios a imágenes.
          **Tecnologías:** JavaScript, HTML, CSS, Docker.

      - layout: left
        border: weak
        title: Encriptador
        additional_links:
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/Jonathan-Med/Encriptador
        description: |
          Herramienta de encriptación que modifica vocales y puede desencriptar texto.
          **Tecnologías:** JavaScript, HTML/CSS.

# Courses
  - title: Cursos
    layout: list
    content:
      - title: Artificial Intelligence Fundamentals
        link: https://www.credly.com/badges/8a135be9-a943-4eb6-a0dd-625be93d5116/public_url
      - title: Containers & Kubernetes Essentials
        link: https://www.credly.com/badges/f4de6c82-752b-4b87-9b06-5926a07f45f8/public_url
      - title: Cybersecurity Fundamentals
        link: https://www.credly.com/badges/11d94319-f12a-4258-bfa2-6409a27c3b76/public_url
      - title: Data Science Foundations
        link: https://www.credly.com/badges/044cadb8-0afa-4fb3-a9ca-b0e4cdc9a111/public_url
      - title: Lista completa de cursos completados
        link: https://drive.google.com/drive/u/3/folders/1wibHSqGQwFsZQPeNO7DX7c0eliB5bU_j

# Education
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Universidad de Guadalajara
        sub_title: Ingeniería en Computación
        caption: 2020 - 2024
        description: |
          GPA: 92.89

    layout: list
    content:
      - layout: top-right
        title: Oracle Next Education Generation 6 (ONEG6)
        sub_title: Backend Specialist
        caption: Enero 2024 - Noviembre 2024

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
